
export const METRO_STATIONS = [
  // --- YELLOW LINE (Samaypur Badli <-> Millennium City Centre) ---
  { id: "yl-1", name: "Samaypur Badli", line: "Yellow" },
  { id: "yl-2", name: "Rohini Sector 18, 19", line: "Yellow" },
  { id: "yl-3", name: "Haiderpur Badli Mor", line: "Yellow" },
  { id: "yl-4", name: "Jahangirpuri", line: "Yellow" },
  { id: "yl-5", name: "Adarsh Nagar", line: "Yellow" },
  { id: "yl-6", name: "Azadpur", line: "Yellow" },
  { id: "yl-7", name: "Model Town", line: "Yellow" },
  { id: "yl-8", name: "GTB Nagar", line: "Yellow" },
  { id: "yl-9", name: "Vishwavidyalaya", line: "Yellow" },
  { id: "yl-10", name: "Vidhan Sabha", line: "Yellow" },
  { id: "yl-11", name: "Civil Lines", line: "Yellow" },
  { id: "yl-12", name: "Kashmere Gate", line: "Yellow" },
  { id: "yl-13", name: "Chandni Chowk", line: "Yellow" },
  { id: "yl-14", name: "Chawri Bazar", line: "Yellow" },
  { id: "yl-15", name: "New Delhi", line: "Yellow" },
  { id: "yl-16", name: "Rajiv Chowk", line: "Yellow" },
  { id: "yl-17", name: "Patel Chowk", line: "Yellow" },
  { id: "yl-18", name: "Central Secretariat", line: "Yellow" },
  { id: "yl-19", name: "Udyog Bhawan", line: "Yellow" },
  { id: "yl-20", name: "Lok Kalyan Marg", line: "Yellow" },
  { id: "yl-21", name: "Jor Bagh", line: "Yellow" },
  { id: "yl-22", name: "Dilli Haat - INA", line: "Yellow" },
  { id: "yl-23", name: "AIIMS", line: "Yellow" },
  { id: "yl-24", name: "Green Park", line: "Yellow" },
  { id: "yl-25", name: "Hauz Khas", line: "Yellow" },
  { id: "yl-26", name: "Malviya Nagar", line: "Yellow" },
  { id: "yl-27", name: "Saket", line: "Yellow" },
  { id: "yl-28", name: "Qutab Minar", line: "Yellow" },
  { id: "yl-29", name: "Chhatarpur", line: "Yellow" },
  { id: "yl-30", name: "Sultanpur", line: "Yellow" },
  { id: "yl-31", name: "Ghitorni", line: "Yellow" },
  { id: "yl-32", name: "Arjan Garh", line: "Yellow" },
  { id: "yl-33", name: "Guru Dronacharya", line: "Yellow" },
  { id: "yl-34", name: "Sikandarpur", line: "Yellow" },
  { id: "yl-35", name: "MG Road", line: "Yellow" },
  { id: "yl-36", name: "IFFCO Chowk", line: "Yellow" },
  { id: "yl-37", name: "Millennium City Centre", line: "Yellow" },

  // --- BLUE LINE (Dwarka Sec 21 <-> Noida/Vaishali) ---
  { id: "bl-1", name: "Dwarka Sector 21", line: "Blue" },
  { id: "bl-2", name: "Dwarka Sector 8", line: "Blue" },
  { id: "bl-3", name: "Dwarka Sector 21", line: "Blue" },
  { id: "bl-4", name: "Dwarka Mor", line: "Blue" },
  { id: "bl-5", name: "Nawada", line: "Blue" },
  { id: "bl-6", name: "Uttam Nagar West", line: "Blue" },
  { id: "bl-7", name: "Uttam Nagar East", line: "Blue" },
  { id: "bl-8", name: "Janakpuri West", line: "Blue" },
  { id: "bl-9", name: "Janakpuri East", line: "Blue" },
  { id: "bl-10", name: "Tilak Nagar", line: "Blue" },
  { id: "bl-11", name: "Subhash Nagar", line: "Blue" },
  { id: "bl-12", name: "Tagore Garden", line: "Blue" },
  { id: "bl-13", name: "Rajouri Garden", line: "Blue" },
  { id: "bl-14", name: "Ramesh Nagar", line: "Blue" },
  { id: "bl-15", name: "Moti Nagar", line: "Blue" },
  { id: "bl-16", name: "Kirti Nagar", line: "Blue" },
  { id: "bl-17", name: "Shadipur", line: "Blue" },
  { id: "bl-18", name: "Patel Nagar", line: "Blue" },
  { id: "bl-19", name: "Rajendra Place", line: "Blue" },
  { id: "bl-20", name: "Karol Bagh", line: "Blue" },
  { id: "bl-21", name: "Jhandewalan", line: "Blue" },
  { id: "bl-22", name: "Ramakrishna Ashram Marg", line: "Blue" },
  { id: "bl-23", name: "Rajiv Chowk", line: "Blue" },
  { id: "bl-24", name: "Barakhamba Road", line: "Blue" },
  { id: "bl-25", name: "Mandi House", line: "Blue" },
  { id: "bl-26", name: "Supreme Court", line: "Blue" },
  { id: "bl-27", name: "Indraprastha", line: "Blue" },
  { id: "bl-28", name: "Yamuna Bank", line: "Blue" },
  { id: "bl-29", name: "Akshardham", line: "Blue" },
  { id: "bl-30", name: "Mayur Vihar-I", line: "Blue" },
  { id: "bl-31", name: "Mayur Vihar Extension", line: "Blue" },
  { id: "bl-32", name: "New Ashok Nagar", line: "Blue" },
  { id: "bl-33", name: "Noida Sector 15", line: "Blue" },
  { id: "bl-34", name: "Noida Sector 16", line: "Blue" },
  { id: "bl-35", name: "Noida Sector 18", line: "Blue" },
  { id: "bl-36", name: "Botanical Garden", line: "Blue" },
  { id: "bl-37", name: "Golf Course", line: "Blue" },
  { id: "bl-38", name: "Noida City Centre", line: "Blue" },
  { id: "bl-39", name: "Noida Electronic City", line: "Blue" },
  { id: "bl-40", name: "Laxmi Nagar", line: "Blue" },
  { id: "bl-41", name: "Nirman Vihar", line: "Blue" },
  { id: "bl-42", name: "Preet Vihar", line: "Blue" },
  { id: "bl-43", name: "Karkar Duma", line: "Blue" },
  { id: "bl-44", name: "Anand Vihar ISBT", line: "Blue" },
  { id: "bl-45", name: "Kaushambi", line: "Blue" },
  { id: "bl-46", name: "Vaishali", line: "Blue" },

  // --- RED LINE (Rithala <-> Shaheed Sthal) ---
  { id: "rl-1", name: "Rithala", line: "Red" },
  { id: "rl-2", name: "Rohini West", line: "Red" },
  { id: "rl-3", name: "Rohini East", line: "Red" },
  { id: "rl-4", name: "Pitampura", line: "Red" },
  { id: "rl-5", name: "Kohat Enclave", line: "Red" },
  { id: "rl-6", name: "Netaji Subhash Place", line: "Red" },
  { id: "rl-7", name: "Keshav Puram", line: "Red" },
  { id: "rl-8", name: "Kanhaiya Nagar", line: "Red" },
  { id: "rl-9", name: "Inderlok", line: "Red" },
  { id: "rl-10", name: "Shastri Nagar", line: "Red" },
  { id: "rl-11", name: "Pratap Nagar", line: "Red" },
  { id: "rl-12", name: "Pul Bangash", line: "Red" },
  { id: "rl-13", name: "Tis Hazari", line: "Red" },
  { id: "rl-14", name: "Kashmere Gate", line: "Red" },
  { id: "rl-15", name: "Shastri Park", line: "Red" },
  { id: "rl-16", name: "Seelampur", line: "Red" },
  { id: "rl-17", name: "Welcome", line: "Red" },
  { id: "rl-18", name: "Shahdara", line: "Red" },
  { id: "rl-19", name: "Mansarovar Park", line: "Red" },
  { id: "rl-20", name: "Jhilmil", line: "Red" },
  { id: "rl-21", name: "Dilshad Garden", line: "Red" },
  { id: "rl-22", name: "Shaheed Sthal", line: "Red" },

  // --- MAGENTA LINE (Janakpuri West <-> Botanical Garden) ---
  { id: "ml-1", name: "Janakpuri West", line: "Magenta" },
  { id: "ml-2", name: "Dabri Mor - Janakpuri South", line: "Magenta" },
  { id: "ml-3", name: "Dashrath Puri", line: "Magenta" },
  { id: "ml-4", name: "Palam", line: "Magenta" },
  { id: "ml-5", name: "Sadar Bazaar Cantonment", line: "Magenta" },
  { id: "ml-6", name: "Terminal 1-IGI Airport", line: "Magenta" },
  { id: "ml-7", name: "Shankar Vihar", line: "Magenta" },
  { id: "ml-8", name: "Vasant Vihar", line: "Magenta" },
  { id: "ml-9", name: "Munirka", line: "Magenta" },
  { id: "ml-10", name: "R.K. Puram", line: "Magenta" },
  { id: "ml-11", name: "IIT Delhi", line: "Magenta" },
  { id: "ml-12", name: "Hauz Khas", line: "Magenta" },
  { id: "ml-13", name: "Panchsheel Park", line: "Magenta" },
  { id: "ml-14", name: "Chirag Delhi", line: "Magenta" },
  { id: "ml-15", name: "Greater Kailash", line: "Magenta" },
  { id: "ml-16", name: "Nehru Enclave", line: "Magenta" },
  { id: "ml-17", name: "Kalkaji Mandir", line: "Magenta" },
  { id: "ml-18", name: "Okhla NSIC", line: "Magenta" },
  { id: "ml-19", name: "Sukhdev Vihar", line: "Magenta" },
  { id: "ml-20", name: "Jamia Millia Islamia", line: "Magenta" },
  { id: "ml-21", name: "Okhla Vihar", line: "Magenta" },
  { id: "ml-22", name: "Jasola Vihar Shaheen Bagh", line: "Magenta" },
  { id: "ml-23", name: "Kalindi Kunj", line: "Magenta" },
  { id: "ml-24", name: "Okhla Bird Sanctuary", line: "Magenta" },
  { id: "ml-25", name: "Botanical Garden", line: "Magenta" },

  // --- PINK LINE (Majlis Park <-> Shiv Vihar) ---
  { id: "pl-1", name: "Majlis Park", line: "Pink" },
  { id: "pl-2", name: "Azadpur", line: "Pink" },
  { id: "pl-3", name: "Shalimar Bagh", line: "Pink" },
  { id: "pl-4", name: "Netaji Subhash Place", line: "Pink" },
  { id: "pl-5", name: "Shakurpur", line: "Pink" },
  { id: "pl-6", name: "Punjabi Bagh West", line: "Pink" },
  { id: "pl-7", name: "ESI - Basaidarapur", line: "Pink" },
  { id: "pl-8", name: "Rajouri Garden", line: "Pink" },
  { id: "pl-9", name: "Mayapuri", line: "Pink" },
  { id: "pl-10", name: "Naraina Vihar", line: "Pink" },
  { id: "pl-11", name: "Delhi Cantt.", line: "Pink" },
  { id: "pl-12", name: "Durgabai Deshmukh South Campus", line: "Pink" },
  { id: "pl-13", name: "Sir M. Vishveshwaraiah Moti Bagh", line: "Pink" },
  { id: "pl-14", name: "Bhikaji Cama Place", line: "Pink" },
  { id: "pl-15", name: "Sarojini Nagar", line: "Pink" },
  { id: "pl-16", name: "Dilli Haat - INA", line: "Pink" },
  { id: "pl-17", name: "South Extension", line: "Pink" },
  { id: "pl-18", name: "Lajpat Nagar", line: "Pink" },
  { id: "pl-19", name: "Vinobapuri", line: "Pink" },
  { id: "pl-20", name: "Ashram", line: "Pink" },
  { id: "pl-21", name: "Sarai Kale Khan - Nizamuddin", line: "Pink" },
  { id: "pl-22", name: "Mayur Vihar-I", line: "Pink" },
  { id: "pl-23", name: "Mayur Vihar Pocket I", line: "Pink" },
  { id: "pl-24", name: "Trilokpuri - Sanjay Lake", line: "Pink" },
  { id: "pl-25", name: "East Vinod Nagar - Mayur Vihar-II", line: "Pink" },
  { id: "pl-26", name: "Mandawali - West Vinod Nagar", line: "Pink" },
  { id: "pl-27", name: "IP Extension", line: "Pink" },
  { id: "pl-28", name: "Anand Vihar ISBT", line: "Pink" },
  { id: "pl-29", name: "Karkarduma", line: "Pink" },
  { id: "pl-30", name: "Karkarduma Court", line: "Pink" },
  { id: "pl-31", name: "Krishna Nagar", line: "Pink" },
  { id: "pl-32", name: "East Azad Nagar", line: "Pink" },
  { id: "pl-33", name: "Welcome", line: "Pink" },
  { id: "pl-34", name: "Jaffrabad", line: "Pink" },
  { id: "pl-35", name: "Maujpur - Babarpur", line: "Pink" },
  { id: "pl-36", name: "Gokulpuri", line: "Pink" },
  { id: "pl-37", name: "Johri Enclave", line: "Pink" },
  { id: "pl-38", name: "Shiv Vihar", line: "Pink" },

  // --- VIOLET LINE (Kashmere Gate <-> Raja Nahar Singh) ---
  { id: "vl-1", name: "Kashmere Gate", line: "Violet" },
  { id: "vl-2", name: "Lal Qila", line: "Violet" },
  { id: "vl-3", name: "Jama Masjid", line: "Violet" },
  { id: "vl-4", name: "Delhi Gate", line: "Violet" },
  { id: "vl-5", name: "ITO", line: "Violet" },
  { id: "vl-6", name: "Mandi House", line: "Violet" },
  { id: "vl-7", name: "Janpath", line: "Violet" },
  { id: "vl-8", name: "Central Secretariat", line: "Violet" },
  { id: "vl-9", name: "Khan Market", line: "Violet" },
  { id: "vl-10", name: "Jawaharlal Nehru Stadium", line: "Violet" },
  { id: "vl-11", name: "Jangpura", line: "Violet" },
  { id: "vl-12", name: "Lajpat Nagar", line: "Violet" },
  { id: "vl-13", name: "Moolchand", line: "Violet" },
  { id: "vl-14", name: "Kailash Colony", line: "Violet" },
  { id: "vl-15", name: "Nehru Place", line: "Violet" },
  { id: "vl-16", name: "Kalkaji Mandir", line: "Violet" },
  { id: "vl-17", name: "Govind Puri", line: "Violet" },
  { id: "vl-18", name: "Harkesh Nagar Okhla", line: "Violet" },
  { id: "vl-19", name: "Jasola Apollo", line: "Violet" },
  { id: "vl-20", name: "Sarita Vihar", line: "Violet" },
  { id: "vl-21", name: "Mohan Estate", line: "Violet" },
  { id: "vl-22", name: "Tughlakabad Station", line: "Violet" },
  { id: "vl-23", name: "Badarpur Border", line: "Violet" },
  { id: "vl-24", name: "Sarai", line: "Violet" },
  { id: "vl-25", name: "NHPC Chowk", line: "Violet" },
  { id: "vl-26", name: "Mewala Maharajpur", line: "Violet" },
  { id: "vl-27", name: "Sector 28", line: "Violet" },
  { id: "vl-28", name: "Badkhal Mor", line: "Violet" },
  { id: "vl-29", name: "Old Faridabad", line: "Violet" },
  { id: "vl-30", name: "Neelam Chowk Ajronda", line: "Violet" },
  { id: "vl-31", name: "Bata Chowk", line: "Violet" },
  { id: "vl-32", name: "Escorts Mujesar", line: "Violet" },
  { id: "vl-33", name: "Sant Surdas (Sihi)", line: "Violet" },
  { id: "vl-34", name: "Raja Nahar Singh", line: "Violet" },
  
  // --- GREEN LINE ---
  { id: "gl-1", name: "Inderlok", line: "Green" },
  { id: "gl-2", name: "Kirti Nagar", line: "Green" },
  { id: "gl-3", name: "Ashok Park Main", line: "Green" },
  { id: "gl-4", name: "Punjabi Bagh", line: "Green" },
  { id: "gl-5", name: "Shivaji Park", line: "Green" },
  { id: "gl-6", name: "Madipur", line: "Green" },
  { id: "gl-7", name: "Paschim Vihar East", line: "Green" },
  { id: "gl-8", name: "Paschim Vihar West", line: "Green" },
  { id: "gl-9", name: "Peeragarhi", line: "Green" },
  { id: "gl-10", name: "Udyog Nagar", line: "Green" },
  { id: "gl-11", name: "Surajmal Stadium", line: "Green" },
  { id: "gl-12", name: "Nangloi", line: "Green" },
  { id: "gl-13", name: "Nangloi Railway Station", line: "Green" },
  { id: "gl-14", name: "Rajdhani Park", line: "Green" },
  { id: "gl-15", name: "Mundka", line: "Green" },
  { id: "gl-16", name: "Mundka Industrial Area", line: "Green" },
  { id: "gl-17", name: "Ghevra Metro Station", line: "Green" },
  { id: "gl-18", name: "Tikri Kalan", line: "Green" },
  { id: "gl-19", name: "Tikri Border", line: "Green" },
  { id: "gl-20", name: "Pandit Shree Ram Sharma", line: "Green" },
  { id: "gl-21", name: "Bahadurgarh City", line: "Green" },
  { id: "gl-22", name: "Brigadier Hoshiyar Singh", line: "Green" },
];

export const LINES = ["Yellow", "Blue", "Red", "Magenta", "Pink", "Violet", "Green", "Airport Express"];